# -*- coding: utf-8 -*-
"""Ruido_Blanco_DP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FRuUrPC_pyNVxA6Zm83E4AGRiRN0uhbd

#***Ruido Blanco***
----
>**Author:**
* Daniela Pinzon
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.tsaplots import plot_acf

"""##***EJERCICIOS RUIDO BLANCO***
----
>Para cada serie:
* Dibujar la serie
* Calcular la media total
* Calcular la varianza en diferentes partes y revisar si tiende a ser constante
* Revisar autocorrelaciones
* Determinar si es ruido blando

##***Data ts_1***
----
"""

ts = pd.read_csv('ts1.csv')

ts

df = pd.DataFrame()

df["t"] = ts["0"].values

df.index = ts.index

# Se dibuja la serie de ts_1
pd.plotting.autocorrelation_plot(df)

# Calcular la media total
mean_total = np.mean(df)

# Se calcula la media total de la serie de tiempo ts_1
print("La media total de ts1 es:", mean_total)

# Calcular la varianza en diferentes partes y revisar si tiende a ser constante
var_1 = np.var(df[:20])
var_2 = np.var(df[20:40])
var_3 = np.var(df[40:80])
var_4 = np.var(df[80:])

print("La varianza en la primera parte es:", var_1)
print("La varianza en la segunda parte es:", var_2)
print("La varianza en la tercera parte es:", var_3)
print("La varianza en la cuarta parte es:", var_4)

# Graficar la serie temporal de ruido blanco
plt.plot(df)
plt.xlabel('Tiempo')
plt.ylabel('Valor')
plt.title('Serie temporal de ruido blanco')
plt.show()

# Revisar autocorrelaciones
plot_acf(df, lags=20)
plt.xlabel('Retraso')
plt.ylabel('Autocorrelación')
plt.title('Autocorrelación de la serie temporal de ruido blanco')
plt.show()

"""##***Data ts_2***
----
"""

ts = pd.read_csv('ts2.csv')

ts

df = pd.DataFrame()

df["t"] = ts["0"].values

df.index = ts.index

# Se dibuja la serie de ts_2
pd.plotting.autocorrelation_plot(df)

# Calcular la media total
mean_total = np.mean(df)

# Se calcula la media total de la serie de tiempo ts_2
print("La media total de ts1 es:", mean_total)

# Calcular la varianza en diferentes partes y revisar si tiende a ser constante
var_1 = np.var(df[:20])
var_2 = np.var(df[20:40])
var_3 = np.var(df[40:80])
var_4 = np.var(df[80:])

print("La varianza en la primera parte es:", var_1)
print("La varianza en la segunda parte es:", var_2)
print("La varianza en la tercera parte es:", var_3)
print("La varianza en la cuarta parte es:", var_4)

# Graficar la serie temporal de ruido blanco
plt.plot(df)
plt.xlabel('Tiempo')
plt.ylabel('Valor')
plt.title('Serie temporal de ruido blanco')
plt.show()

# Revisar autocorrelaciones
plot_acf(df, lags=20)
plt.xlabel('Retraso')
plt.ylabel('Autocorrelación')
plt.title('Autocorrelación de la serie temporal de ruido blanco')
plt.show()

"""##***Data ts_3***
----
"""

ts = pd.read_csv('ts3.csv')

ts

df = pd.DataFrame()

df["t"] = ts["0"].values

df.index = ts.index

# Se dibuja la serie de ts_3
pd.plotting.autocorrelation_plot(df)

# Calcular la media total
mean_total = np.mean(df)

# Se calcula la media total de la serie de tiempo ts_3
print("La media total de ts1 es:", mean_total)

# Calcular la varianza en diferentes partes y revisar si tiende a ser constante
var_1 = np.var(df[:20])
var_2 = np.var(df[20:40])
var_3 = np.var(df[40:80])
var_4 = np.var(df[80:])

print("La varianza en la primera parte es:", var_1)
print("La varianza en la segunda parte es:", var_2)
print("La varianza en la tercera parte es:", var_3)
print("La varianza en la cuarta parte es:", var_4)

# Graficar la serie temporal de ruido blanco
plt.plot(df)
plt.xlabel('Tiempo')
plt.ylabel('Valor')
plt.title('Serie temporal de ruido blanco')
plt.show()

# Revisar autocorrelaciones
plot_acf(df, lags=20)
plt.xlabel('Retraso')
plt.ylabel('Autocorrelación')
plt.title('Autocorrelación de la serie temporal de ruido blanco')
plt.show()

"""##***Conclusion***
----

>* Posemos concluir que el ruido blanco es una señal aleatoria que se utiliza en el análisis de series temporales y en otras áreas de la estadística y la econometría.

>* Los valores en la serie temporal t3 son independientes e idénticamente distribuidos , asi confirmamos que es una serie de ruido blanco

>* Las autocorrelaciones son una medida útil para analizar la estructura de una serie temporal. En el caso del ruido blanco, no se espera encontrar ninguna estructura en sus autocorrelaciones. En el caso del t1 y t3 fue fundamental para evidenciar que no eran ruido blanco

>* El ruido blanco se utiliza en muchos campos de la estadística y la ciencia como un modelo de referencia para comparar con otras series temporales en este caso t3 seria la unica serie temporal de ruido blanco

"""